MangaOnline/MangaOnline/Pages/Public/AddChapter.cshtml.cs
using MangaOnline.Enum;
using MangaOnline.Extensions;
using MangaOnline.Hubs;
using MangaOnline.Models;
using Microsoft.AspNetCore.Mvc;
using MangaOnline.Pages.Auth;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;

namespace MangaOnline.Pages.Public
{
    public class AddChapterModel : AbstractModel
    {
        private readonly MangaOnlineV1DevPRN221Context _context;
        private readonly ILogicHandler _logicHandler;
        private IHubContext<NotificationHub> HubContext;

        public AddChapterModel(MangaOnlineV1DevPRN221Context mangaOnlineV1DevContext, ILogicHandler logicHandler,
            IHubContext<NotificationHub> HubContext)
        {
            _context = mangaOnlineV1DevContext;
            _logicHandler = logicHandler;
            this.HubContext = HubContext;
        }
        [BindProperty] public bool isStatus { get; set; }
        public Guid? MangaId { get; set; }
        public Manga manga { get; set; }

        public IActionResult OnGet(string id)
        {
            if (!CheckRoleUser(new[] { UserRoleEnum.Admin.ToString() }))
                return RedirectToPage("/Error");
            manga = _context.Mangas.FirstOrDefault(x => x.Id == Guid.Parse(id));
            ViewData["done"] = 0;
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!CheckRoleUser(new[] { UserRoleEnum.Admin.ToString() }))
                return RedirectToPage("/Error");

            IFormFile file = Request.Form.Files.GetFile("fileUp");
            //IFormFile file = Request.Form.Files.GetFile("wpName");

            Chaptere chaptere = new Chaptere();
            chaptere.ChapterNumber = int.Parse(Request.Form["ChapNumber"]);
            chaptere.Id = Guid.NewGuid();
            chaptere.SubId = 0;
            chaptere.MangaId = Guid.Parse(Request.Form["mangaId"]);
            chaptere.Name = " Chapter " + Request.Form["ChapNumber"];
            chaptere.CreatedAt = DateTimeOffset.Now;
            chaptere.Status = isStatus == true ? 0 : 1;
            chaptere.IsActive = true;
            chaptere.FilePdf = _logicHandler.CreatePDF(file);

            _context.Chapteres.AddAsync(chaptere);
            _context.SaveChanges();
            manga = _context.Mangas.FirstOrDefault(x => x.Id == chaptere.MangaId);
            ViewData["done"] = 1;
            await HubContext.Clients.All.SendAsync("LoadNotification", manga.Id);

            return RedirectToPage("/Public/DetailManga", new { id = chaptere.MangaId });
        }
    }
}

MangaOnline/MangaOnline/Pages/Public/CategoriesList.cshtml.cs
using MangaOnline.Enum;
using MangaOnline.Models;
using MangaOnline.Pages.Manage;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MangaOnline.Pages.Public;

public class CategoriesList : PageModel
{
    private readonly MangaOnlineV1DevPRN221Context _context;

    public List<Manga> listManga = new();
    public Dictionary<Guid, List<Category>> mangaCategoryDict = new();
    public List<Category> Categories = new();

    public string Genre { get; set; }
    public string Status { get; set; }
    public string Sort { get; set; }
    public string Rating { get; set; }

    public int LastPage { get; set; }
    public int PageSize { get; set; } = 12;
    public int PageIndex { get; set; } = 1;

    public CategoriesList(MangaOnlineV1DevPRN221Context context)
    {
        _context = context;
    }

    public void OnGet(string? cateName, string genre, string status, string sort, string rating, int index)
    {
        var mList = _context.Mangas.ToList();
        var cmList = _context.CategoryMangas.ToList();
        var cList = _context.Categories.ToList();

        if (!string.IsNullOrEmpty(cateName))
        {
            Genre = cateName;
        }
        else
        {
            Genre = string.IsNullOrEmpty(genre) ? "Tất cả thể loại" : genre;
        }

        Status = string.IsNullOrEmpty(status) ? "Tất cả" : status;
        Sort = string.IsNullOrEmpty(sort) ? "Ngày cập nhật" : sort;
        Rating = string.IsNullOrEmpty(rating) ? "Tất cả" : rating;

        var statusEnum = Status switch
        {
            "Hoàn thành" => (int)MangaStatusEnum.Done,
            "Đang cập nhật" => (int)MangaStatusEnum.Updating,
            "Dừng cập nhật" => (int)MangaStatusEnum.StopUpdating,
            _ => -1
        };

        var strSort = Sort switch
        {
            "Ngày cập nhật" => "ModifiedAt",
            "Top view" => "ViewCount",
            "Top followers" => "FollowCount",
            _ => "ModifiedAt"
        };

        if (!Genre.Equals("Tất cả thể loại"))
        {
            listManga = (from m in mList
                join cm in cmList
                    on m.Id equals cm.MangaId
                join c in cList
                    on cm.CategoryId equals c.Id
                where c.Name == Genre
                select m).ToList();
        }
        else
        {
            listManga = _context.Mangas.OrderBy(x => x.ModifiedAt).ToList();
        }

        if (statusEnum != -1)
        {
            listManga = listManga.Where(x => x.Status == statusEnum).ToList();
        }

        if (!Rating.Equals("Tất cả"))
        {
            var starInt = int.Parse(rating);
            listManga = listManga.Where(x => x.Star == starInt).ToList();
        }

        LastPage = listManga.Count / PageSize;
        if (listManga.Count % PageSize > 0)
        {
            LastPage += 1;
        }

        index = index == 0 ? 1 : index;
        PageIndex = index;
        if (index <= LastPage)
        {
            listManga = listManga.Skip(PageSize * (index - 1)).Take(PageSize).ToList();
        }
        switch (strSort)
        {
            case "ViewCount":
                listManga = listManga.OrderByDescending(x => x.ViewCount).ToList();
                break;
            case "ModifiedAt":
                listManga = listManga.OrderByDescending(x => x.ModifiedAt).ToList();
                break;
            case "FollowCount":
                listManga = listManga.OrderByDescending(x => x.FollowCount).ToList();
                break;
            default:
                listManga= listManga.OrderByDescending(x => x.ModifiedAt).ToList();
                break;
        }


        foreach (var manga in listManga)
        {
            var cateResult = from c in cList
                join cm in cmList
                    on c.Id equals cm.CategoryId
                join m in mList
                    on cm.MangaId equals m.Id
                where m.Id == manga.Id
                select c;
            mangaCategoryDict.Add(manga.Id, cateResult.ToList());
        }

        Categories = _context.Categories.ToList();
    }
}

MangaOnline/MangaOnline/Pages/Public/DetailManga.cshtml.cs
using MangaOnline.ModelCore;
using MangaOnline.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MangaOnline.Pages.Public
{
    public class DetailMangaModel : PageModel
    {
        private readonly MangaOnlineV1DevPRN221Context db;
        public Manga manga = new Manga();
        public bool isFollowed = false;
        public List<Manga> ListManga = new List<Manga>();
        public Dictionary<Guid, List<Category>> mangaCategoryDict = new Dictionary<Guid, List<Category>>();
        public List<Comment> ListComment = new List<Comment>();
        public Comment comment = new Comment();

        private UserCookie user = new UserCookie();

        public DetailMangaModel(MangaOnlineV1DevPRN221Context db)
        {
            this.db = db;
        }

        public UserCookie GetUser()
        {
            var accessToken = HttpContext.Request.Cookies["USER_DATA"];
            if (accessToken is not null)
            {
                user = JsonConvert.DeserializeObject<UserCookie>(accessToken);
            }
            else
            {
                user = null;
            }

            return user;
        }

        public void OnGet(string id)
        {
            user = GetUser();
            manga = db.Mangas.FirstOrDefault(x => x.Id == Guid.Parse(id));

            var author = db.Authors.FirstOrDefault(x => x.Id == manga.AuthorId);
            manga.Author = author;

            var chapters = db.Chapteres.Where(x => x.MangaId == manga.Id).OrderBy(x=>x.ChapterNumber).ToList();
            manga.Chapteres = chapters;

            var mList = db.Mangas.ToList();
            ListManga = mList.Where(x => x.Id != Guid.Parse(id)).ToList();

            var cmList = db.CategoryMangas.ToList();
            var cList = db.Categories.ToList();

            foreach (var ma in mList)
            {
                var cateResult = from c in cList
                    join cm in cmList
                        on c.Id equals cm.CategoryId
                    join m in mList
                        on cm.MangaId equals m.Id
                    where m.Id == ma.Id
                    select c;
                mangaCategoryDict.Add(ma.Id, cateResult.ToList());
            }

            if (user != null)
            {
                var followManga = db.FollowLists.FirstOrDefault(x => x.UserId == user.Id && x.MangaId == manga.Id);
                if (followManga != null)
                {
                    isFollowed = true;
                }
            }
            else
            {
                isFollowed = false;
            }

            manga.ViewCount++;
            db.SaveChanges();

            ListComment = db.Comments
                .Include(x => x.Manga)
                .Include(x => x.User)
                .Where(x => x.MangaId == manga.Id && x.IsActive == true).ToList();
        }

        public IActionResult OnPostFollow(string mangaId)
        {
            user = GetUser();
            manga = db.Mangas.FirstOrDefault(x => x.Id == Guid.Parse(mangaId));

            var followManga = new FollowList()
            {
                Id = Guid.NewGuid(),
                UserId = user.Id,
                MangaId = manga.Id
            };
            db.FollowLists.Add(followManga);
            db.SaveChanges();

            manga.FollowCount++;
            db.SaveChanges();
            
            // add list mangaFollowId on cookie
            var listMangaIdFollow = db.FollowLists
                .Where(x => x.UserId == user.Id)
                .Select(x=>x.MangaId).ToList();
            if (listMangaIdFollow.Count>0)
            {
                var followStr = "";
                foreach (var fId in listMangaIdFollow)
                {
                    followStr += fId;
                    if (!fId.Equals(listMangaIdFollow[^1]))
                    {
                        followStr += ",";
                    }
                }
                Response.Cookies.Append("MANGA_FOLLOW", followStr);
            }
            // add list mangaFollowId on cookie

            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }

        public IActionResult OnPostUnfollow(string mangaId)
        {
            user = GetUser();
            manga = db.Mangas.FirstOrDefault(x => x.Id == Guid.Parse(mangaId));

            var followManga = db.FollowLists.FirstOrDefault(x => x.UserId == user.Id && x.MangaId == manga.Id);
            db.FollowLists.Remove(followManga);
            db.SaveChanges();

            manga.FollowCount--;
            db.SaveChanges();
            // add list mangaFollowId on cookie
            var listMangaIdFollow = db.FollowLists
                .Where(x => x.UserId == user.Id)
                .Select(x=>x.MangaId).ToList();
            if (listMangaIdFollow.Count>0)
            {
                var followStr = "";
                foreach (var fId in listMangaIdFollow)
                {
                    followStr += fId;
                    if (!fId.Equals(listMangaIdFollow[^1]))
                    {
                        followStr += ",";
                    }
                }
                Response.Cookies.Append("MANGA_FOLLOW", followStr);
            }
            // add list mangaFollowId on cookie
            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }

        public IActionResult OnPostLikeComment(string commentId, string mangaId)
        {
            var commentObj = db.Comments.FirstOrDefault(x => x.Id == Guid.Parse(commentId));
            commentObj.LikedCount++;
            db.SaveChanges();
            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }

        public IActionResult OnPostUnlikeComment(string commentId, string mangaId)
        {
            var commentObj = db.Comments.FirstOrDefault(x => x.Id == Guid.Parse(commentId));
            commentObj.DislikedCount++;
            db.SaveChanges();
            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }

        public IActionResult OnPostAddComment(string comment, string mangaId)
        {
            user = GetUser();
            if(user == null)
            {
               return RedirectToPage("/Auth/AuthLogin");
            }    
            var newComment = new Comment()
            {
                Id = Guid.NewGuid(),
                MangaId = Guid.Parse(mangaId),
                UserId = user.Id,
                Content = comment,

                CreatedAt = DateTimeOffset.Now,
                LikedCount = 0,
                DislikedCount = 0,
                IsActive = true
            };
            db.Comments.Add(newComment);
            db.SaveChanges();
            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }

        public IActionResult OnPostReadContinues(string mangaId)
        {
            var listChapter = Request.Cookies["LIST_CHAPTER"];
            if (listChapter != null)
            {
                var listChapterId = JsonConvert.DeserializeObject<List<ChapterByManga>>(listChapter);
                var chapter = listChapterId?.FirstOrDefault(x => x.MangaId.ToString() == mangaId);
                if (chapter != null)
                {
                    var chapterId = chapter.ChapterId;
                    var chapterWantTo = db.Chapteres.FirstOrDefault(x => x.Id == chapterId);
                    if (chapterWantTo != null)
                    {
                        return RedirectToPage("/Public/DetailChapter", new { id = chapterWantTo.Id });
                    }
                }
            }

            var chapterFirst = db.Chapteres.Where(x => x.MangaId.ToString() == mangaId)
                .OrderBy(x => x.ChapterNumber)
                .FirstOrDefault();
            if (chapterFirst != null)
            {
                return RedirectToPage("/Public/DetailChapter", new { id = chapterFirst.Id });
            }

            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }

        public IActionResult OnPostFirstChapter(string mangaId)
        {
            var chapterFirst = db.Chapteres.Where(x => x.MangaId.ToString() == mangaId)
                .OrderByDescending(x => x.ChapterNumber)
                .FirstOrDefault();
            if (chapterFirst != null)
            {
                return RedirectToPage("/Public/DetailChapter", new { id = chapterFirst.Id });
            }
            return RedirectToPage("/Public/DetailManga", new { id = mangaId });
        }
    }
}

MangaOnline/MangaOnline/Pages/Public/TestPublic.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MangaOnline.Pages.Public;

public class TestPublic : PageModel
{
    public void OnGet()
    {
        
    }
}

MangaOnline/MangaOnline/Pages/Public/AddChapter.cshtml
@page "/Public/AddChapter/{id}"
@model MangaOnline.Pages.Public.AddChapterModel
@{
    Layout = "_Layout";
    ViewData["title"] = "Add Chapter";
}
<link rel="stylesheet" href="~/css/AddManga.css">
<div class="sign section--bg">
    <div class="container-add">

        <div class="row">
            <div class="col-12">

                <div class="sign__content" style="padding-top: 100px;">
                    <!-- add form -->
                    <form method="post" class="sign__form form-addManga" enctype="multipart/form-data">
                        <div class="title-addManga">
                            <h1>Thêm Chapter</h1>
                        </div>
                        <div class="col-12" style="display: flex;">
                            <div class="col-sm-4">
                                <div class="input-group-add">
                                    <p class="input-title">Tên Manga</p>
                                    <input type="text" readonly value="@Model.manga.Name" class="sign__input">
                                    <input type="text" name="mangaId" hidden value="@Model.manga.Id">
                                </div>
                                <div class="input-group-add">
                                    <p class="input-title">Chapter Number</p>
                                    <input type="number" name="ChapNumber" class="sign__input">
                                </div>
                                <div class="sign__group sign__group--checkbox">
                                    <input type="checkbox" id="isStatus" name="isStatus" asp-for="@Model.isStatus" value="true">
                                    <label for="isStatus" class="input-title">Người dùng VIP</label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="input-group-add">
                                    <p class="input-title" required>UpLoad</p>
                                    <input type="file" id="fileInput"
                                           class="input-file-image"
                                           accept=".pdf" name="fileUp" onchange="setfilename(this.value)" />
                                    <input type="text" name="wpName" id="wpName" class="sign__input">
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div>
                                    <div style="max-height: 120px;margin-bottom:10px">
                                        <button class="sign__btn" id="submitBtn" type="submit">Thêm chapter</button>
                                    </div>
                                    <div style="display:none;color: green;font-size:12px;" id="done_success">Add thành công chapter mới</div>
                                    <div style="display:none" id="take_notice">@ViewData["done"]</div>
                                </div>                          
                            </div>

                        </div>
                    </form>
                    <!-- add form -->
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.onload = async () => {
        console.log(document.getElementById("take_notice").innerHTML)
        if (document.getElementById("take_notice").innerHTML === "1") {
            onNotice();
        }
    }
    function onNotice() {
        console.log('noti');
        document.getElementById("done_success").style.display = "block";
        sleep(1000);

    }
    function sleep(ms) {
        return new Promise(resolve => setTimeout(() => {
            document.getElementById("done_success").style.display = "none";
        }, ms));
    }
    function setfilename(val) {
        filename = val.split('\\').pop().split('/').pop();
        document.getElementById('wpName').value = filename;
    }

</script>

MangaOnline/MangaOnline/Pages/Public/DetailChapter.cshtml
@page
@model MangaOnline.Pages.Public.DetailChapter

@{
    Layout = null;
}
@{
    Layout = "_Layout";
    ViewData["Title"] = "Đọc truyện";
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div style="margin-top: 93px;">
    <style>
        #manga-pdf{
            width: 100%;
            height: 95vh;
        }
    </style>
    <iframe id="manga-pdf" src="~/pdf/@Model.Chaptere" frameborder="0"></iframe>
</div>
</body>
</html>

MangaOnline/MangaOnline/Pages/Public/FollowedList.cshtml
@page
@model MangaOnline.Pages.Public.FollowedListModel
@using MangaOnline.ModelCore
@using MangaOnline.Models
@using Newtonsoft.Json


@{
    Layout = "_Layout";
}

@{
    var listManga = Model.listManga;
    var mangaCategoryDict = Model.mangaCategoryDict;

    var accessToken = HttpContext.Request.Cookies["USER_DATA"];
    UserCookie user2 = new UserCookie();
    var avatarLink = "/lib/img/avatar-default.jpg";
    if (accessToken is not null)
    {
        user2 = JsonConvert.DeserializeObject<UserCookie>(accessToken);
        if (user2.Avartar is not null)
        {
            avatarLink = "/image/avartar-user/" + user2.Avartar;
        }
    }
    else
    {
        user2 = null;
    }

}

<link rel="stylesheet" href="~/css/DetailManga.css">

<!-- page title -->
<section class="section section--first section--bg" data-bg="img/section/section.jpg">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section__wrap">
                    <!-- section title -->
                    <h2 class="section__title">Truyện đang theo dõi</h2>
                    <!-- end section title -->
                    <!-- breadcrumb -->
                    <ul class="breadcrumb">
                        <li class="breadcrumb__item">
                            <a asp-page="/Index">Trang chủ</a>
                        </li>
                        <li class="breadcrumb__item breadcrumb__item--active">Theo Dõi</li>
                    </ul>
                    <!-- end breadcrumb -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end page title -->
@if (user2 is null)
{
    <div style="display: flex; justify-content: center; align-items: center">
        <p class="breadcrumb__item breadcrumb__item--active" style="margin-left: 16px; margin-top: 16px">
            Bạn nên <a style="color: #ff55a5;" class="login_link" asp-page="/Auth/AuthLogin">Đăng nhập</a>
            để truy cập truyện đã theo dõi của bạn ở bất cứ đâu
        </p>
    </div>
}
else
{
    if (Model.ListFollow.Count == 0)
    {
        <div style="display: flex; justify-content: center; align-items: center">
            <p class="breadcrumb__item breadcrumb__item--active" style="margin-left: 16px; margin-top: 16px">
                Bạn chưa theo dõi truyện nào cả. Để theo dõi truyện, nhấn vào <u>Theo dõi</u> như hình bên:
            </p>
            <p>
                <img src="/image/huong-dan-theo-doi-truyen.png" alt="Hướng dẫn theo dõi truyện tranh"
                     width="660" style="margin-left: 16px; margin-top: 16px" />
            </p>
        </div>
    }
    else
    {
        <!-- catalog -->
        <div class="catalog" style="padding-top: 20px">
            <div class="container">
                <div class="row">
                    <!-- card -->
                    @foreach (var manga in listManga)
                    {
                        <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                            <div class="card">
                                <div class="card__cover">
                                    <img src="/image/manga-image/@manga.Image" alt="@manga.Name" style="height: 237.03px; width: 160px;">
                                    <a asp-page="/Public/DetailManga" asp-route-id="@manga.Id" class="card__play">
                                        <i class="icon ion-ios-play"></i>
                                    </a>
                                </div>
                                <div class="card__content">
                                    <h3 class="card__title">
                                        <a asp-page="/Public/DetailManga" asp-route-id="@manga.Id">@manga.Name</a>
                                    </h3>
                                    <span class="card__category">
                                        @{
                                            var categories = mangaCategoryDict[manga.Id];
                                            foreach (var category in categories)
                                            {
                                                <a asp-page="/Public/CategoriesList" asp-route-cateName="@category.Name">@category.Name</a>
                                            }
                                        }
                                    </span>
                                    <span class="card__rate"><i class="icon ion-ios-star"></i>@manga.Star</span>
                                    <form method="post" asp-page-handler="unfollow">
                                        <input name="mangaId" value="@manga.Id" hidden />
                                        <button type="submit" class="button-unfollow">
                                            <i class="fa fa-times"></i>
                                            <span>Bỏ theo dõi</span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                    <!-- end card -->                  
                </div>
            </div>
        </div>
        <!-- end catalog -->
    }
}
<script>
$(document).ready(function () {
    $('#noti-follow2').hide();
    $.cookie('NotiFollowStatus', '');
})
</script>

MangaOnline/MangaOnline/Pages/Public/TestPublic.cshtml
@page
@model MangaOnline.Pages.Public.TestPublic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>